// <auto-generated />
using System;
using FeatureFlags.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FeatureFlags.Api.Data.Migrations
{
    [DbContext(typeof(FeatureFlagsDbContext))]
    [Migration("20260910212948_AddFeatureVariantsAndAllocation")]
    partial class AddFeatureVariantsAndAllocation
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FeatureFlags.Api.Data.Entities.FeatureAllocationGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("FeatureFlagId")
                        .HasColumnType("int");

                    b.Property<string>("GroupName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("VariantName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("FeatureFlagId", "VariantName", "GroupName")
                        .IsUnique();

                    b.ToTable("FeatureAllocationGroups", "FeatureFlags");
                });

            modelBuilder.Entity("FeatureFlags.Api.Data.Entities.FeatureAllocationPercentile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("FeatureFlagId")
                        .HasColumnType("int");

                    b.Property<double>("From")
                        .HasColumnType("float");

                    b.Property<double>("To")
                        .HasColumnType("float");

                    b.Property<string>("VariantName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("FeatureFlagId");

                    b.ToTable("FeatureAllocationPercentiles", "FeatureFlags");
                });

            modelBuilder.Entity("FeatureFlags.Api.Data.Entities.FeatureAllocationUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("FeatureFlagId")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("VariantName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("FeatureFlagId", "VariantName", "UserId")
                        .IsUnique();

                    b.ToTable("FeatureAllocationUsers", "FeatureFlags");
                });

            modelBuilder.Entity("FeatureFlags.Api.Data.Entities.FeatureFilter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("FeatureFlagId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("ParametersJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FeatureFlagId");

                    b.ToTable("FeatureFilters", "FeatureFlags");
                });

            modelBuilder.Entity("FeatureFlags.Api.Data.Entities.FeatureFlag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AllocationSeed")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("DefaultWhenDisabled")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("DefaultWhenEnabled")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("Enabled")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("RequirementType")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("FeatureFlags", "FeatureFlags");
                });

            modelBuilder.Entity("FeatureFlags.Api.Data.Entities.FeatureStoreMeta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<long>("StoreVersion")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("FeatureStoreMeta", "FeatureFlags");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            StoreVersion = 0L
                        });
                });

            modelBuilder.Entity("FeatureFlags.Api.Data.Entities.FeatureVariant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ConfigurationJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("FeatureFlagId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("StatusOverride")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.HasKey("Id");

                    b.HasIndex("FeatureFlagId", "Name")
                        .IsUnique();

                    b.ToTable("FeatureVariants", "FeatureFlags");
                });

            modelBuilder.Entity("FeatureFlags.Api.Data.Entities.FeatureAllocationGroup", b =>
                {
                    b.HasOne("FeatureFlags.Api.Data.Entities.FeatureFlag", "FeatureFlag")
                        .WithMany("AllocationGroups")
                        .HasForeignKey("FeatureFlagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FeatureFlag");
                });

            modelBuilder.Entity("FeatureFlags.Api.Data.Entities.FeatureAllocationPercentile", b =>
                {
                    b.HasOne("FeatureFlags.Api.Data.Entities.FeatureFlag", "FeatureFlag")
                        .WithMany("AllocationPercentiles")
                        .HasForeignKey("FeatureFlagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FeatureFlag");
                });

            modelBuilder.Entity("FeatureFlags.Api.Data.Entities.FeatureAllocationUser", b =>
                {
                    b.HasOne("FeatureFlags.Api.Data.Entities.FeatureFlag", "FeatureFlag")
                        .WithMany("AllocationUsers")
                        .HasForeignKey("FeatureFlagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FeatureFlag");
                });

            modelBuilder.Entity("FeatureFlags.Api.Data.Entities.FeatureFilter", b =>
                {
                    b.HasOne("FeatureFlags.Api.Data.Entities.FeatureFlag", "FeatureFlag")
                        .WithMany("Filters")
                        .HasForeignKey("FeatureFlagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FeatureFlag");
                });

            modelBuilder.Entity("FeatureFlags.Api.Data.Entities.FeatureVariant", b =>
                {
                    b.HasOne("FeatureFlags.Api.Data.Entities.FeatureFlag", "FeatureFlag")
                        .WithMany("Variants")
                        .HasForeignKey("FeatureFlagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FeatureFlag");
                });

            modelBuilder.Entity("FeatureFlags.Api.Data.Entities.FeatureFlag", b =>
                {
                    b.Navigation("AllocationGroups");

                    b.Navigation("AllocationPercentiles");

                    b.Navigation("AllocationUsers");

                    b.Navigation("Filters");

                    b.Navigation("Variants");
                });
#pragma warning restore 612, 618
        }
    }
}
